# Singularity images used by the pipeline
# --------------------------------------------------------------------------------
singularity:
  umicollapse             : docker://dfernand/umicollapse:07506e661496033ca059e04a7771633b7b70721f
  cellranger_rna_sif      : docker://biotechpedro/cellranger:8.0.1
  cellranger_multiome_sif : docker://dfernand/cellranger_arc:2.0.2
  cellranger_atac_sif     : docker://dfernand/cellranger_atac:2.1.0
  seurat_sif              : docker://dfernand/cloneranger:300525


# Cellranger count parameters
# --------------------------------------------------------------------------------
cellranger_count:
  # 10x pipeline: Must be GEX (rnaseq), ATAC or ARC (multiome, RNA + ATAC).
  10x_pipeline : "GEX"
  introns: True
  create_bam: False
  # Genome references for GEX and ARC
  genome_reference_gex: /data/qscd/Users/SEQUENCING_DATA/References/Cellranger/refdata-gex-mm10-2020-A/
  genome_refrerence_arc: /data/qscd/Users/SEQUENCING_DATA/References/Cellranger/refdata-gex-mm10-2020-A/ # would not work but not going to be used
  # Extra parameters for cellranger. Non-secondary is used to avoid cellranger
  # to perform UMAP, clustering, DEGs... 
  extra_parameters_atac: "--nosecondary"
  extra_parameters_rna: "--nosecondary" # add "--nosecondary --create-bam <true|false>" if v8.0.1
  extra_parameters_arc: ""


# Parameters regarding preprocessing of Seurat object
# --------------------------------------------------------------------------------
preprocessing:
  # Min number of cells that must express a gene to include it in the final matrix
  min_cells_gene : 5
  # human or mouse
  species: "mouse"
  mito_pattern   : "^mt-"
  ribo_pattern   : "^Rpl|^Rps"
  marker_genes   :
    - Procr
    - Mecom
    - Pf4
    - Elane
    - Flt3
    - Lyz2
    - Akr1c13
    - Ctsg
    - Car1
    - Ms4a2
    - Mki67
    - Plac8
    - Mcpt8
    - Mmp16
    - Ncam2
    - Tgfbr3
    - Tcf15
    - Nupr1
    - Rnf220
    - Clu


# Location of configuration files. This MUST NOT be modified.
# --------------------------------------------------------------------------------
units        : config/samples/units.tsv
sample_config: config/samples/sample_config.tsv
resources    : config/resources.yaml
larry_config : config/larry_config.yaml
cell_hashing : config/cellhash_config.yaml